CREATE TABLE GAMES (
    id serial PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    user_id uuid REFERENCES USERS (id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE USER_GAMES (
    id serial PRIMARY KEY,
    user_id uuid REFERENCES USERS (id) ON DELETE CASCADE NOT NULL,
    game_id INT REFERENCES GAMES (id) ON DELETE CASCADE NOT NULL
);
