name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: pentagame
          postgresql user: pentagame
          postgresql password: pentagame
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          cp ci/ci.toml pentagame.toml
          cargo install diesel_cli --features postgres
          make setup
          make db-setup
      - name: Build
        run: make ci-build
      # There are no application specific test at the moment
      # - name: Run tests
      #  run: make ci-test
